### ISSUE TITLE
compare.df1_unq_rows and compare.df2_unq_rows don't provide the correct index of unique rows from respective dataFrames 

### ISSUE THREAD

**Issue by NiteshOO7** [capitalone/datacompy#112] opened 2021-08-09 08:51 UTC
Row indexes are not right while trying to find out unique rows which are missing in respective dataFrames.
compare.df1_unq_rows and compare.df2_unq_rows returns the unique rows which are missing in respective dataFrames but their index are not returned correctly. Please have a look at this issue. I would be really great if the right indexes are returned on using mentioned functions.

**Comment by fdosani** [comment] 2021-08-09 11:22
@NiteshOO7 could you provide a code snippet and output of the issue you are facing so we can try and reproduce exactly what you are facing?

**Comment by NiteshOO7** [comment] 2021-08-09 12:13
**Kindly find code snippet below:**

=================================================================================
import pandas as pd
import datacompy

df_old_original = pd.DataFrame([[1, 1, 1, 1], [2, 2, 2, 2], [7, 7, 7, 7], [3, 3, 3, 3], [4, 4, 4, 4], [5, 5, 5, 5], [6, 6, 6, 6]], columns=['A', 'B', 'C', 'D'], index=[0, 1, 2, 3, 4, 5, 6], dtype=object)
df_new_original = pd.DataFrame([[None, None, None, None], [1, 1, 1, 1], [2, 2, 2, 2], [8, 8, 8, 8], [3, 3, 3, 3], [4, 4, 4, 4], [5, 5, 5, 5], [None, None, None, None]], columns=['A', 'B', 'C', 'D'], index=[0, 1, 2, 3, 4, 5, 6, 7], dtype=object)

compare = datacompy.Compare(df_old_original, df_new_original, join_columns=['A', 'B', 'C', 'D'], abs_tol=0, rel_tol=0, df1_name='Old', df2_name='New')
changes_in_old_df = compare.df1_unq_rows
changes_in_new_df = compare.df2_unq_rows
print(changes_in_old_df)
print(changes_in_new_df)
===============================================================================
Here in this code "compare.df1_unq_rows" gives correct indexes of unique rows but compare.df2_unq_rows doesn't return the correct indexes of unique rows.
![image](https://user-images.githubusercontent.com/37611047/128704358-f540b31f-e585-441e-8a60-8a7592e24f6b.png)

**Comment by fdosani** [comment] 2021-08-09 14:58
Thanks, will take a look into this.

**Comment by fdosani** [comment] 2021-08-09 15:20
Ok, so maybe a bit of primer as to what is happening. I think depending on how to look at this it could be a not so great UX, but I'm not sure if this is a bug. In the above example you have 2 dataframes:

old
```
   A  B  C  D
0  1  1  1  1
1  2  2  2  2
2  7  7  7  7
3  3  3  3  3
4  4  4  4  4
5  5  5  5  5
6  6  6  6  6
```

new
```
0  None  None  None  None
1     1     1     1     1
2     2     2     2     2
3     8     8     8     8
4     3     3     3     3
5     4     4     4     4
6     5     5     5     5
7  None  None  None  None
```

when we join these together we are joining on the following columns: `join_columns=['A', 'B', 'C', 'D']`. In order to get all the items which match and don't match we need to do a outer join to get this information. It is creating a new dataframe in the backend which looks like this: 

```
      a     b     c     d      _merge
0   1.0   1.0   1.0   1.0        both
1   2.0   2.0   2.0   2.0        both
2   7.0   7.0   7.0   7.0   left_only
3   3.0   3.0   3.0   3.0        both
4   4.0   4.0   4.0   4.0        both
5   5.0   5.0   5.0   5.0        both
6   6.0   6.0   6.0   6.0   left_only
7  None  None  None  None  right_only
8  None  None  None  None  right_only
9     8     8     8     8  right_only
```

We really have no choice with the new dataframe to reindex it with the left side in this case taking priority. I guess my main question is are you trying to join back to some other dataframe? If so you should use your original `join_columns=['A', 'B', 'C', 'D']` to do so.

Happy to discuss this a bit further but I don't think there is a good way to preserve those original indexes since it needs to expand out the dataset here to find out what is common and unique between the two.

cc: @theianrobertson @jborchma @elzzhu any thoughts on this?

**Comment by NiteshOO7** [comment] 2021-08-10 04:24
My requirement is if a row is unique in either of the dataFrames then insert blank row to the other dataFrame i.e. if a row is left_only then insert a blank row in right side as per the index of the row which is left_only. 
That's why I need original index of unique rows. I would be really great if you can help me out in this.

I got your point why compare.df2_unq_rows doesn't return the correct indexes of unique rows as left side is taking priority. 
Can you please explain why  "compare.df1_unq_rows" returned indexes as (5, 7) instead of (2, 7) when I have modified the case little bit?

**Comment by fdosani** [comment] 2021-08-10 16:32
The second example looks like this: 

```
       a     b     c     d      _merge
0    1.0   1.0   1.0   1.0        both
1    2.0   2.0   2.0   2.0        both
2    7.0   7.0   7.0   7.0        both
3    7.0   7.0   7.0   7.0        both
4    3.0   3.0   3.0   3.0        both
5    4.0   4.0   4.0   4.0        both
6    5.0   5.0   5.0   5.0        both
7    6.0   6.0   6.0   6.0   left_only
8   None  None  None  None  right_only
9   None  None  None  None  right_only
10     8     8     8     8  right_only
```

I think the index is something you should not rely on since it doesn't correspond to the original dataset, since this is a new dataframe. You can just run the following to get the output from above:

```
outer_join = compare.df1.merge(
                  compare.df2, how="outer", suffixes=("_df1", "_df2"), indicator=True, **{"on": compare.join_columns}
                 )
```

The `_merge` columns gives you what you want to insert the blank rows etc.

**Comment by NiteshOO7** [comment] 2021-08-11 06:34
As per your explanation  "compare.df1_unq_rows" should return below line:
![image](https://user-images.githubusercontent.com/37611047/128979654-c03c0acd-937e-4dcb-99aa-c5b70488b43d.png)
But instead it is retuning below lines:
![image](https://user-images.githubusercontent.com/37611047/128979818-d02bd293-9de8-4e1e-be99-22568632de67.png)

I hope I understood it correctly. 

I tried this merge function before considering taking help of datacompy library. Merge function doesn't help me for my requirement. Datacompy library still works better than merge function because it tells that the line (7 7 7 7) which is flagged as both by merge function, is a line which is missing in other dataframe. If we place both dataframes side by side we will also realize that should be expected behavior. 
![image](https://user-images.githubusercontent.com/37611047/128980202-6c1ec0c8-1be9-44cf-aff7-b6d587b1c31d.png)

**Comment by fdosani** [comment] 2021-08-11 12:33
yeah that seems to be a bug of some sort. Looking into that specific case. But I do think to your previous question about the indexes, the index in the outputs isn't intended to be used as you want, so you might need to figure out an alternative way to get what you need. The new dataframe is created joining both via an outer join so the index doesn't preserve from the original datasets.

I'll look into the extra column being returned and put in a fix for that. Hope this all helps and makes sense.

**Comment by fdosani** [comment] 2021-08-11 12:42
So my previous output was incorrect, since I only isolated some bits of the code. It should have been: 
```
DEBUG:datacompy.core:       a     b     c     d      _merge
0    1.0   1.0   1.0   1.0        both
1    2.0   2.0   2.0   2.0        both
2    7.0   7.0   7.0   7.0        both
3    3.0   3.0   3.0   3.0        both
4    4.0   4.0   4.0   4.0        both
5    7.0   7.0   7.0   7.0   left_only
6    5.0   5.0   5.0   5.0        both
7    6.0   6.0   6.0   6.0   left_only
8   None  None  None  None  right_only
9      8     8     8     8  right_only
10  None  None  None  None  right_only
```

Which makes sense since you have  `7,7,7,7` twice as keys. First one joins with the right one and the second one is on its own.

**Comment by NiteshOO7** [comment] 2021-08-12 08:25
Now it make sense. Can you please provide me what line of code you run to get above result?

**Comment by fdosani** [comment] 2021-08-16 17:09
To run the above code I just pip installed datacompy in editable mode. (Clone the repo and `pip install -e .`)
Then add some debug logging statements like the following: 

```
LOG.debug(outer_join). # <--- like this
LOG.debug("Selecting df1 unique rows")
self.df1_unq_rows = outer_join[outer_join["_merge"] == "left_only"][df1_cols].copy()
self.df1_unq_rows.columns = self.df1.columns
```

I'm going to close this issue, feel free to reopen it if you feel there is more of a discussion to be had. I don't think there is any action item of changes we can really make.

**Closed by fdosani** 2021-08-16 17:09 UTC

**Comment by lkacenja** [comment] 2021-12-11 00:13
Sorry for reviving a closed issue here. I'm working on a project to show before and after changes to large datasets as part of a QA process for our extract transform load pipeline. I also want to be able to show rows missing from the left or right dataset. I'm a bit of a python and pandas noob as well. Sorry for that.

The example code you provided above works really well. However when I debug outer_join it does not contain *_match columns. The only way I can think to get them is to compare once to get the outer_join and then create two new data frames that contain the empty rows on either side. Then I'd have to compare a second time. Is there a better way?

Thanks!
